# -*- coding: utf-8 -*-
{
    'name': "Employee Clinic SIIC",
    'summary': """  Custom Application for Employee Clinic SIIC""",
    'description': """ Employee Clinic SIIC """,
    'author': "SIIC",
    'category': 'Human Resources/Employee Clinic',
    'depends': ['base', 'multi_branch', 'hr', 'stock'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/data.xml',
        'views/clinic_menu.xml',
        'views/product_views.xml',
        'views/partner_views.xml',
        'views/clinic_detection.xml',
        'views/employee_medication.xml',
        'report/clinic_detection_template.xml',
        'report/clinic_detection_report.xml',
    ],
    'images': ['static/description/icon.png'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
